Add files via upload

diff --git a/erpnext16/Dockerfile b/erpnext16/Dockerfile
--- a/erpnext16/Dockerfile
+++ b/erpnext16/Dockerfile
@@ -151,8 +151,6 @@ USER root
 WORKDIR /root
 
 # 安装支持软件
-ARG MARIADB_CONFIG_FILE=/etc/mysql/mariadb.conf.d/99-erpnext.cnf
-ARG SUPERVISOR_CONFIG_DIR=/etc/supervisor/conf.d
 RUN apt-get update \
     && curl -LsS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | sudo bash -s -- --mariadb-server-version=11.8 \
     && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
@@ -162,74 +160,100 @@ RUN apt-get update \
         nginx \
         supervisor \
     && sudo rm -rf /var/lib/apt/lists/* \
-    && echo "[mysqld]" >> ${MARIADB_CONFIG_FILE} \
-    && echo "character-set-client-handshake=FALSE" >> ${MARIADB_CONFIG_FILE} \
-    && echo "character-set-server=utf8mb4" >> ${MARIADB_CONFIG_FILE} \
-    && echo "collation-server=utf8mb4_unicode_ci" >> ${MARIADB_CONFIG_FILE} \
-    && echo "bind-address=0.0.0.0" >> ${MARIADB_CONFIG_FILE} \
-    && echo "innodb_file_per_table=1" >> ${MARIADB_CONFIG_FILE} \
-    && echo "innodb_file_format=Barracuda" >> ${MARIADB_CONFIG_FILE} \
-    && echo "innodb_large_prefix=ON" >> ${MARIADB_CONFIG_FILE} \
-    && echo "" >> ${MARIADB_CONFIG_FILE} \
-    && echo "[mysql]" >> ${MARIADB_CONFIG_FILE} \
-    && echo "default-character-set=utf8mb4" >> ${MARIADB_CONFIG_FILE} \
-    && echo "[program:mariadb]" >> ${SUPERVISOR_CONFIG_DIR}/mariadb.conf \
-    && echo "command=/usr/sbin/mariadbd --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib/mysql/plugin --user=mysql --skip-log-error" >> ${SUPERVISOR_CONFIG_DIR}/mariadb.conf \
-    && echo "priority=1" >> ${SUPERVISOR_CONFIG_DIR}/mariadb.conf \
-    && echo "autostart=true" >> ${SUPERVISOR_CONFIG_DIR}/mariadb.conf \
-    && echo "autorestart=true" >> ${SUPERVISOR_CONFIG_DIR}/mariadb.conf \
-    && echo "numprocs=1" >> ${SUPERVISOR_CONFIG_DIR}/mariadb.conf \
-    && echo "startretries=10" >> ${SUPERVISOR_CONFIG_DIR}/mariadb.conf \
-    && echo "stopwaitsecs=10" >> ${SUPERVISOR_CONFIG_DIR}/mariadb.conf \
-    && echo "redirect_stderr=true" >> ${SUPERVISOR_CONFIG_DIR}/mariadb.conf \
-    && echo "stdout_logfile_maxbytes=1024MB" >> ${SUPERVISOR_CONFIG_DIR}/mariadb.conf \
-    && echo "stdout_logfile_backups=10" >> ${SUPERVISOR_CONFIG_DIR}/mariadb.conf \
-    && echo "stdout_logfile=/var/run/log/supervisor_mysql.log" >> ${SUPERVISOR_CONFIG_DIR}/mariadb.conf \
-    && echo "[program:nginx]" >> ${SUPERVISOR_CONFIG_DIR}/nginx.conf \
-    && echo "" >> ${SUPERVISOR_CONFIG_DIR}/nginx.conf \
-    && echo "command=/usr/sbin/nginx -g 'daemon off;'" >> ${SUPERVISOR_CONFIG_DIR}/nginx.conf \
-    && echo "autorestart=true" >> ${SUPERVISOR_CONFIG_DIR}/nginx.conf \
-    && echo "autostart=true" >> ${SUPERVISOR_CONFIG_DIR}/nginx.conf \
-    && echo "stderr_logfile=/var/run/log/supervisor_nginx_error.log" >> ${SUPERVISOR_CONFIG_DIR}/nginx.conf \
-    && echo "stdout_logfile=/var/run/log/supervisor_nginx_stdout.log" >> ${SUPERVISOR_CONFIG_DIR}/nginx.conf \
-    && echo "environment=ASPNETCORE_ENVIRONMENT=Production" >> ${SUPERVISOR_CONFIG_DIR}/nginx.conf \
-    && echo "user=root" >> ${SUPERVISOR_CONFIG_DIR}/nginx.conf \
-    && echo "stopsignal=INT" >> ${SUPERVISOR_CONFIG_DIR}/nginx.conf \
-    && echo "startsecs=10" >> ${SUPERVISOR_CONFIG_DIR}/nginx.conf \
-    && echo "startretries=5" >> ${SUPERVISOR_CONFIG_DIR}/nginx.conf \
-    && echo "stopasgroup=true" >> ${SUPERVISOR_CONFIG_DIR}/nginx.conf
+    # 生成数据库配置文件
+    && echo "[mysqld]" > /etc/mysql/mariadb.conf.d/99-erpnext.cnf \
+    && echo "character-set-client-handshake=FALSE" >> /etc/mysql/mariadb.conf.d/99-erpnext.cnf \
+    && echo "character-set-server=utf8mb4" >> /etc/mysql/mariadb.conf.d/99-erpnext.cnf \
+    && echo "collation-server=utf8mb4_unicode_ci" >> /etc/mysql/mariadb.conf.d/99-erpnext.cnf \
+    && echo "bind-address=0.0.0.0" >> /etc/mysql/mariadb.conf.d/99-erpnext.cnf \
+    && echo "innodb_file_per_table=1" >> /etc/mysql/mariadb.conf.d/99-erpnext.cnf \
+    && echo "innodb_file_format=Barracuda" >> /etc/mysql/mariadb.conf.d/99-erpnext.cnf \
+    && echo "innodb_large_prefix=ON" >> /etc/mysql/mariadb.conf.d/99-erpnext.cnf \
+    && echo "" >> /etc/mysql/mariadb.conf.d/99-erpnext.cnf \
+    && echo "[mysql]" >> /etc/mysql/mariadb.conf.d/99-erpnext.cnf \
+    && echo "default-character-set=utf8mb4" >> /etc/mysql/mariadb.conf.d/99-erpnext.cnf \
+    # 生成supervisor管理mariadb配置文件
+    && echo "[program:mariadb]" > /etc/supervisor/conf.d/mariadb.conf \
+    && echo "command=/usr/sbin/mariadbd --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib/mysql/plugin --user=mysql --skip-log-error" >> /etc/supervisor/conf.d/mariadb.conf \
+    && echo "priority=1" >> /etc/supervisor/conf.d/mariadb.conf \
+    && echo "autostart=true" >> /etc/supervisor/conf.d/mariadb.conf \
+    && echo "autorestart=true" >> /etc/supervisor/conf.d/mariadb.conf \
+    && echo "numprocs=1" >> /etc/supervisor/conf.d/mariadb.conf \
+    && echo "startretries=10" >> /etc/supervisor/conf.d/mariadb.conf \
+    && echo "stopwaitsecs=10" >> /etc/supervisor/conf.d/mariadb.conf \
+    && echo "redirect_stderr=true" >> /etc/supervisor/conf.d/mariadb.conf \
+    && echo "stdout_logfile_maxbytes=1024MB" >> /etc/supervisor/conf.d/mariadb.conf \
+    && echo "stdout_logfile_backups=10" >> /etc/supervisor/conf.d/mariadb.conf \
+    && echo "stdout_logfile=/var/run/log/supervisor_mysql.log" >> /etc/supervisor/conf.d/mariadb.conf \
+    # 生成supervisor管理nginx配置文件
+    && echo "[program:nginx]" > /etc/supervisor/conf.d/nginx.conf \
+    && echo "" >> /etc/supervisor/conf.d/nginx.conf \
+    && echo "command=/usr/sbin/nginx -g 'daemon off;'" >> /etc/supervisor/conf.d/nginx.conf \
+    && echo "autorestart=true" >> /etc/supervisor/conf.d/nginx.conf \
+    && echo "autostart=true" >> /etc/supervisor/conf.d/nginx.conf \
+    && echo "stderr_logfile=/var/run/log/supervisor_nginx_error.log" >> /etc/supervisor/conf.d/nginx.conf \
+    && echo "stdout_logfile=/var/run/log/supervisor_nginx_stdout.log" >> /etc/supervisor/conf.d/nginx.conf \
+    && echo "environment=ASPNETCORE_ENVIRONMENT=Production" >> /etc/supervisor/conf.d/nginx.conf \
+    && echo "user=root" >> /etc/supervisor/conf.d/nginx.conf \
+    && echo "stopsignal=INT" >> /etc/supervisor/conf.d/nginx.conf \
+    && echo "startsecs=10" >> /etc/supervisor/conf.d/nginx.conf \
+    && echo "startretries=5" >> /etc/supervisor/conf.d/nginx.conf \
+    && echo "stopasgroup=true" >> /etc/supervisor/conf.d/nginx.conf \
+    # 生成supervisor管理frappe配置文件修正补丁,开启生产模式时链接到配置目录。
+    && mkdir -p /etc/supervisor/custom \
+    && echo "[program:frappe-bench-frappe-schedule]" > /etc/supervisor/custom/frappe_fix.conf  \
+    && echo "environment=" >> /etc/supervisor/custom/frappe_fix.conf  \
+    && echo "    PYTHONPATH=/home/frappe/.bench:/home/frappe/.pyenv/versions/3.14.2/lib/python3.14/site-packages:/home/frappe/frappe-bench/env/lib/python3.14/site-packages," >> /etc/supervisor/custom/frappe_fix.conf  \
+    && echo "    PATH=/home/frappe/.local/bin:/home/frappe/.pyenv/shims:/home/frappe/.pyenv/bin:%(ENV_PATH)s" >> /etc/supervisor/custom/frappe_fix.conf  \
+    && echo "" >> /etc/supervisor/custom/frappe_fix.conf  \
+    && echo "[program:frappe-bench-frappe-short-worker]" >> /etc/supervisor/custom/frappe_fix.conf  \
+    && echo "environment=" >> /etc/supervisor/custom/frappe_fix.conf  \
+    && echo "    PYTHONPATH=/home/frappe/.bench:/home/frappe/.pyenv/versions/3.14.2/lib/python3.14/site-packages:/home/frappe/frappe-bench/env/lib/python3.14/site-packages," >> /etc/supervisor/custom/frappe_fix.conf  \
+    && echo "    PATH=/home/frappe/.local/bin:/home/frappe/.pyenv/shims:/home/frappe/.pyenv/bin:%(ENV_PATH)s" >> /etc/supervisor/custom/frappe_fix.conf  \
+    && echo "" >> /etc/supervisor/custom/frappe_fix.conf  \
+    && echo "[program:frappe-bench-frappe-long-worker]" >> /etc/supervisor/custom/frappe_fix.conf  \
+    && echo "environment=" >> /etc/supervisor/custom/frappe_fix.conf  \
+    && echo "    PYTHONPATH=/home/frappe/.bench:/home/frappe/.pyenv/versions/3.14.2/lib/python3.14/site-packages:/home/frappe/frappe-bench/env/lib/python3.14/site-packages," >> /etc/supervisor/custom/frappe_fix.conf  \
+    && echo "    PATH=/home/frappe/.local/bin:/home/frappe/.pyenv/shims:/home/frappe/.pyenv/bin:%(ENV_PATH)s" >> /etc/supervisor/custom/frappe_fix.conf 
 
 USER frappe
 WORKDIR /home/frappe
 
-ENV PYTHONPATH=/home/frappe/.bench:/home/frappe/.pyenv/versions/3.14.2/lib/python3.14/site-packages:/home/frappe/frappe-bench/env/lib/python3.14/site-packages
-ENV PATH=/home/frappe/.local/bin:/home/frappe/.pyenv/shims:/home/frappe/.pyenv/bin:${PATH}
+# ENV PYTHONPATH=/home/frappe/.bench:/home/frappe/.pyenv/versions/3.14.2/lib/python3.14/site-packages:/home/frappe/frappe-bench/env/lib/python3.14/site-packages
+# ENV PATH=/home/frappe/.local/bin:/home/frappe/.pyenv/shims:/home/frappe/.pyenv/bin:${PATH}
+
 RUN sudo /usr/bin/supervisord -c /etc/supervisor/supervisord.conf \
     && sleep 10 \
-    && bench init --frappe-branch version-16 --ignore-exist frappe-bench --frappe-path \
+    # 开启数据库的远程访问权限，有安全风险。请自行做好风险管控。
+    && sudo mariadb -uroot -e "CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY 'Pass1234';" \
+    && sudo mariadb -uroot -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;" \
+    && sudo mariadb -uroot -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'Pass1234';" \
+    && bench init --frappe-branch version-16 --ignore-exist frappe-bench \
     && cd /home/frappe/frappe-bench \
     && bench get-app --branch version-16 "https://github.com/frappe/erpnext" \
     && bench new-site --mariadb-root-username "root" --mariadb-root-password Pass1234 --db-password Pass1234 --admin-password admin site1.local \
     && bench config http_timeout 6000 \
     && bench config serve_default_site on \
     && bench use site1.local \
-    && bench start > bench-start.log 2>&1 & \
+    && (bench start > bench-start.log 2>&1 &) \
     && sleep 10 \
     && bench --site site1.local install-app erpnext \
-    # 容器中运行fail2ban需要特权模式，这里注释掉代码开启生产模式时将不再安装fail2ban。防火墙需要宿主机自行维护。 \
+    # 容器中运行fail2ban需要特权模式，这里注释掉检测及安装fail2ban的代码，否则将由于权限不足而安装失败。防火墙需要宿主机自行维护。 \
     && n=$(sed -n "/^[[:space:]]*if not which.*fail2ban-client/=" "/home/frappe/.bench/bench/config/production_setup.py") \
     && sudo sed -i "${n} s/^/#&/" "/home/frappe/.bench/bench/config/production_setup.py" \
-    && let n++ \
+    && n=$((n + 1)) \
     && sudo sed -i "${n} s/^/#&/" "/home/frappe/.bench/bench/config/production_setup.py" \
-    && sudo bench setup production frappe --yes \
+    # 将修正补丁链接到配置目录
+    && sudo ln -s /etc/supervisor/custom/frappe_fix.conf /etc/supervisor/conf.d/frappe_fix.conf \
+    && i=0 \
+    && until [ -f /etc/supervisor/conf.d/frappe-bench.conf ] || [ $i -ge 9 ]; do \
+        sudo -E env PATH="$PATH" bench setup production frappe --yes; i=$((i+1)); done; \
+        [ -f /etc/supervisor/conf.d/frappe-bench.conf ] || (echo "生产模式配置失败" && exit 1) \
     && pip cache purge \
     && npm cache clean --force \
     && yarn cache clean \
     && bench clear-cache \
-    && bench clear-website-cache \
-    && sudo /usr/bin/supervisorctl status \
-    && cd /home/frappe/frappe-bench \
-    && bench version
+    && bench clear-website-cache
 
 EXPOSE 3306 80
 
@@ -240,3 +264,14 @@ STOPSIGNAL SIGTERM
 
 ENTRYPOINT ["/bin/bash", "-c"]
 CMD ["sudo /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf"]
+
+FROM erpnext AS test
+
+USER frappe
+WORKDIR /home/frappe/frappe-bench
+
+RUN sudo /usr/bin/supervisord -c /etc/supervisor/supervisord.conf \
+    && sleep 10 \
+    && ps aux \
+    && sudo /usr/bin/supervisorctl status \
+    && bench version
